[versions]
kotlin-logger = "2.1.20"
logback = "6.4"
postgresql = "42.4.0"
jsonwebtoken = "0.11.5"

[libraries]
kotlin-logger = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logger" }
logback = {module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
jsonwebtoken-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jsonwebtoken"}
jsonwebtoken-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jsonwebtoken"}