server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
  server:
      waitTimeInMsWhenSyncEmpty: 0
