server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
#  instance:
#    hostname: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
  server:
      waitTimeInMsWhenSyncEmpty: 0
