management.endpoints.web.exposure.include: "*"
server:
  port: 8888

spring:
  rabbitmq:
    addresses: ${RABBITMQ_SERVICE_SERVICE_HOST:localhost}
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qweezique/spring-cloud-config-server.git
          clone-on-start: true
          default-label: master
          search-paths: '{profile}'
    bus:
      enabled: true

eureka:
  instance:
    instance-id: config-${random.uuid}
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
    enabled: true