server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
