server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qweezique/spring-cloud-config-server
          clone-on-start: true
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    registerWithEureka: true
    fetchRegistry: false
    enabled: true